civitai_api_key : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
ngrok_token     : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
preset          : anime

gdrive:
  output_path : "/content/drive/MyDrive/SD/"
  assets_path : "/content/drive/MyDrive/SD/loras"
  enable_backup_assets : true
  enable_restore_assets: true
  backup_assets :
    - backup_dir  : "/content/drive/MyDrive/SD/loras"
      working_dir : "/content/Fooocus/models/loras"
    - backup_dir  : "/content/drive/MyDrive/SD/embedded"
      working_dir : "/content/Fooocus/models/embedded"

models:
  - dir: "/content/Fooocus/models/checkpoints/"
    models:
      # https://civitai.com/models/260267?modelVersionId=403131
      "Animagine V3.1 "     : "https://huggingface.co/cagliostrolab/animagine-xl-3.1/resolve/main/animagine-xl-3.1.safetensors"
loras:
  - dir: "/content/Fooocus/models/loras/chara/"
    loras:
      "Genshin - Fischl"    : "https://civitai.com/models/187745"
      "Genshin - Hutao"     : "https://civitai.com/models/163219"

  - dir: "/content/Fooocus/models/loras/other/"
    loras:
      "Anime Style Enchancer"              : "https://huggingface.co/Linaqruf/style-enhancer-xl-lora/resolve/main/style-enhancer-xl.safetensors"
      "Anime Detailer"                     : "https://huggingface.co/Linaqruf/anime-detailer-xl-lora/resolve/main/anime-detailer-xl.safetensors"
      "Aesthetic Anime LoRA"               : "https://civitai.com/models/295100"
      "PE Anime Background / Landscapes"   : "https://civitai.com/models/137169"
      "Artist Style: Mika Pikazo"          : "https://civitai.com/models/275291"

embeddings:
  - dir: "/content/Fooocus/models/embeddings/"
    embeddings:
      "negativeXL"       : "https://civitai.com/models/118418"

presets:
  - file_name : "anime.json"
    preset:
      checkpoint_downloads              : {}
      default_cfg_scale                 : 7.0
      default_image_number              : 1
      default_overwrite_step            : 28
      default_save_metadata_to_images   : True
      default_metadata_scheme           : "a1111"
      default_aspect_ratio              : "896*1152"
      default_max_image_number          : 32
      default_sampler                   : "euler_ancestral"
      default_styles                    :
        - "Fooocus V2"
        - "Animagine Heavy V3.1"
        - "Animagine Cinematic"

      default_loras:
        - [ true, "None", 0.35 ]
        - [ true, "None", 0.5 ]
        - [ true, "None", 0.5 ]
        - [ true, "None", 0.5 ]
        - [ true, "None", 0.5 ]
        - [ true, "None", 0.5 ]

      default_prompt :
        1girl, fischl, genshin impact, sitting, crossing legs, moody, looking down,
        looking at viewer, throne, indoors, lower angle, symmetrical

      default_prompt_negative :
        nsfw, longbody, lowres, bad anatomy, bad hands, missing fingers, pubic hair, extra digit,
        fewer digits, cropped, worst quality, low quality, very displeasing

styles:
  - file_name: "animagine_style.json"
    styles:
      - name: "Animagine Standard v3.0"
        prompt: "{prompt}, masterpiece, best quality"
        negative_prompt: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name"

      - name: "Animagine Standard v3.1"
        prompt: "{prompt}, masterpiece, best quality, very aesthetic, absurdres"
        negative_prompt: "lowres, (bad), text, error, fewer, extra, missing, worst quality, jpeg artifacts, low quality, watermark, unfinished, displeasing, oldest, early, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract]"

      - name: "Animagine Light v3.1"
        prompt: "{prompt}, (masterpiece), best quality, very aesthetic, perfect face"
        negative_prompt: "(low quality, worst quality:1.2), very displeasing, 3d, watermark, signature, ugly, poorly drawn"

      - name: "Animagine Heavy v3.1"
        prompt: "{prompt}, (masterpiece), (best quality), (ultra-detailed), very aesthetic, illustration, disheveled hair, perfect composition, moist skin, intricate details"
        negative_prompt: "longbody, lowres, bad anatomy, bad hands, missing fingers, pubic hair, extra digit, fewer digits, cropped, worst quality, low quality, very displeasing"

      - name: "Animagine Cinematic"
        prompt: "{prompt}, cinematic still, emotional, harmonious, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy"
        negative_prompt: "cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured"

      - name: "Animagine Photographic"
        prompt: "{prompt}, cinematic photo, 35mm photograph, film, bokeh, professional, 4k, highly detailed"
        negative_prompt: "drawing, painting, crayon, sketch, graphite, impressionist, noisy, blurry, soft, deformed, ugly"

      - name: "Animagine Anime"
        prompt: "{prompt}, anime artwork, anime style, key visual, vibrant, studio anime, highly detailed"
        negative_prompt: "photo, deformed, black and white, realism, disfigured, low contrast"

      - name: "Animagine Manga"
        prompt: "{prompt}, manga style, vibrant, high-energy, detailed, iconic, Japanese comic style"
        negative_prompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, Western comic style"

      - name: "Animagine Digital Art"
        prompt: "{prompt}, concept art, digital artwork, illustrative, painterly, matte painting, highly detailed"
        negative_prompt: "photo, photorealistic, realism, ugly"

      - name: "Animagine Pixel art"
        prompt: "{prompt}, pixel-art, low-res, blocky, pixel art style, 8-bit graphics"
        negative_prompt: "sloppy, messy, blurry, noisy, highly detailed, ultra textured, photo, realistic"

      - name: "Animagine Fantasy art"
        prompt: "{prompt}, ethereal fantasy concept art, magnificent, celestial, ethereal, painterly, epic, majestic, magical, fantasy art, cover art, dreamy"
        negative_prompt: "photographic, realistic, realism, 35mm film, dslr, cropped, frame, text, deformed, glitch, noise, noisy, off-center, deformed, cross-eyed, closed eyes, bad anatomy, ugly, disfigured, sloppy, duplicate, mutated, black and white"

      - name: "Animagine Neonpunk"
        prompt: "{prompt}, neonpunk style, cyberpunk, vaporwave, neon, vibes, vibrant, stunningly beautiful, crisp, detailed, sleek, ultramodern, magenta highlights, dark purple shadows, high contrast, cinematic, ultra detailed, intricate, professional"
        negative_prompt: "painting, drawing, illustration, glitch, deformed, mutated, cross-eyed, ugly, disfigured"

      - name: "Animagine 3D Model"
        prompt: "{prompt}, professional 3d model, octane render, highly detailed, volumetric, dramatic lighting"
        negative_prompt: "ugly, deformed, noisy, low poly, blurry, painting"

wildcards:
  - file_name: "chara.txt"
    wildcard: |
      fischl \(genshin impact\)
      lumine \(genshin impact\)
      yoimiya \(genshin impact\)

  - file_name: "image_composition.txt"
    wildcard: |
      portrait
      upper body
      lower body
      cowboy shot
      feet out of frame
      full body
      wide shot
      very wide shot
      close-up
      cut-in
      cropped legs
      head out of frame
      cropped torso
      cropped arms
      cropped shoulders
      profile
      group profile

unused:
  - "/content/Fooocus/sdxl_styles/sdxl_styles_sai.json"
  - "/content/Fooocus/sdxl_styles/sdxl_styles_mre.json"
  - "/content/Fooocus/sdxl_styles/sdxl_styles_twri.json"
  - "/content/Fooocus/sdxl_styles/sdxl_styles_diva.json"
  - "/content/Fooocus/sdxl_styles/sdxl_styles_marc_k3nt3l.json"